export const projects = [
  {
    id: 1,
    slug: "gta-hotels",
    name: "GTA Hotels",
    category: "Web Development",
    type: "web",
    tools: "Next.js · Firebase · Tailwind . ALAT Payment Integration . Resend . Automated Email Notifications . Admin Management System",
    desc: "Full hotel booking system with room management, availability calendar, online reservations, and payment integration.",
    image: "/gtaHotel.png",
    screenBg: "bg-blue-100",
    tag: "bg-blue-50 text-blue-600",
    year: "2026",
    featured: true,
    status: "Completed",
    link: "https://gtahotelikeja.com",
    caseStudy: {
      challenge:
        "GTA Hotels needed to move off manual, phone-based bookings and give guests a fast, reliable way to check room availability and pay online — without losing the polish expected from a hospitality brand.",
      solutions: [
        "Redesigned the client's static WordPress site into a dynamic, fully functional hotel management system",
        "Built a full booking system with real-time room availability checking",
        "Integrated ALAT for secure online payments",
        "Added room, booking, user, and review management, including the ability for guests to leave reviews",
        "Let guests book as a guest or a signed-in account — no compulsory sign-up required",
        "Implemented SEO and image optimization",
        "Delivered a responsive, clean, modern UI/UX",
        "Added Role-Based Access Control (RBAC)",
        "Automated booking confirmations and notifications via Resend",
        "Delivered an admin dashboard for staff to manage rooms, rates, and reservations without developer help",
      ],
      gallery: ["/gtaHotel.png"],
      testimonial: {
        quote:
          "The website loads faster compared to our previous website. The image doesn't even take time to load. You also took your time to look into what we want and delivered exactly what we needed.",
        name: "Mr Femi",
        role: "IT Engineer, GTA Hotels Group",
      },
    },
  },
  {
    id: 25,
    slug: "gta-restaurant-management-system",
    name: "GTA Restaurant Management System",
    category: "Web Development",
    type: "web",
    tools: "Next.js · Firebase · Tailwind . ALAT Payment Integration . Resend . Automated Email Notifications . Admin Management System",
    desc: "Full restaurant management system with menu management, order processing, online reservations, and payment integration.",
    image: "/gtaRestaurant.png",
    screenBg: "bg-blue-100",
    tag: "bg-blue-50 text-blue-600",
    year: "2026",
    featured: true,
    status: "Completed",
    link: "https://restaurant.gtahotelikeja.com",
    caseStudy: {
      challenge:
        "As a sister property to GTA Hotels, the restaurant team needed the same level of digital reliability — a way to manage the menu, take orders, and handle reservations online instead of juggling it manually.",
      solutions: [
        "Built a restaurant management system covering menu and menu category management",
        "Added QR code menu access for guests to browse and order",
        "Built order processing with integrated payment via ALAT",
        "Let guests order without requiring an account sign-up",
        "Delivered a fully responsive design",
        "Added online table reservations",
        "Automated order and reservation email notifications via Resend",
        "Delivered an admin management system consistent with the GTA Hotels platform",
      ],
      gallery: ["/gtaRestaurant.png"],
      testimonial: null,
    },
  },
  {
    id: 2,
    slug: "that-local-girl",
    name: "That Local Girl (Web App)",
    category: "Web Development",
    type: "web",
    tools: "Next.js · Supabase · Tailwind · Stripe · Carrier · Resend . Google Maps API . Multiple Payment Methods . Multicurrency Support",
    desc: "E-commerce mobile app with product listings, cart, Stripe payment integration, Carrier integration, real-time shipping fee calculation, and order tracking.",
    image: "/thatlocalgirl.png",
    screenBg: "bg-blue-100",
    tag: "bg-blue-50 text-blue-600",
    year: "2025",
    featured: true,
    status: "Completed",
    link: "https://thatlocalgirl.com",
    caseStudy: {
      challenge:
        "That Local Girl needed a proper e-commerce storefront that could handle real logistics — accurate shipping costs, multiple currencies for a cross-border customer base, and a checkout that just works.",
      solutions: [
        "Migrated the client off WordPress to a fully custom e-commerce platform built with Next.js, Firebase, and Tailwind CSS",
        "Built product listings, cart, and checkout with Stripe, supporting multiple payment methods and multi-currency",
        "Connected a carrier integration for real-time shipping fee calculation, with the Google Maps API for accurate delivery addresses",
        "Added order, product, and review management",
        "Built a points and referral system — customers earn points and redeem them toward purchases",
        "Added analytics and an AI-powered support system",
        "Implemented detailed SEO and image optimization",
        "Delivered a fully responsive, mobile-friendly design with Role-Based Access Control (RBAC)",
        "Automated order and account emails via Resend",
      ],
      gallery: ["/thatlocalgirl.png"],
      testimonial: {
        quote:
          "I love the UI of my E-commerce website, the payment integration and the admin management system. And the fact I can add products myself. And also the support of multiple currencies.",
        name: "Olusanya Rofiat",
        role: "Founder, That Local Girl",
      },
    },
  },
  {
    id: 21,
    slug: "dwelcore",
    name: "Dwelcore",
    category: "Web Development",
    type: "web",
    tools: "Next.js · Tailwind · Firebase · Stripe · Figma · Resend . Multiple Payment Methods . Multicurrency Support",
    desc: "A platform that allows users browse home plans, purchase and modify home plans in the US. Supports multiple payment method.",
    image: "/dwelcore.png",
    screenBg: "bg-blue-100",
    tag: "bg-blue-50 text-blue-600",
    year: "2026",
    featured: true,
    status: "Completed",
    link: "https://dwelcore.com",
    caseStudy: {
      challenge:
        "Dwelcore needed to let US customers browse home plans, customize them, and pay securely online — the kind of platform WordPress couldn't reliably support.",
      solutions: [
        "Redesigned the client's WordPress e-commerce site into a fully custom home plan platform built with Next.js",
        "Designed the product in Figma before development to align on UX early",
        "Built an AI-powered home plan search assistant, plus smart search functionality",
        "Added plan listing with the ability to reverse (mirror) home plans and a build cost calculator",
        "Integrated Stripe with support for multiple payment methods and multi-currency",
        "Added Google Analytics for event tracking",
        "Implemented SEO and image optimization, with full mobile responsiveness",
        "Added a live chat feature and automated transactional notifications via Resend",
        "Built out admin management and analytics for users, orders, plans, categories, and styles",
        "Added abandoned cart and favorites management, plan modification request management, and subscriber management",
        "Added audit logs and Role-Based Access Control (RBAC)",
      ],
      gallery: ["/dwelcore.png"],
      testimonial: {
        quote:
          "I love the fact that you are very professional. You communicated effectively and help us achieve all we can't achieve on WordPress.",
        name: "No Lans",
        role: "Project Manager, Dwelcore",
      },
    },
  },
  {
    id: 22,
    slug: "yordson-apartments",
    name: "Yordson Apartments",
    category: "Web Development",
    type: "web",
    tools: "Next.js · Tailwind · Firebase · Paystack  · Resend",
    desc: "A hotel website with room listings, booking system, and payment integration for a seamless user experience.",
    image: "/yordsonapartments.png",
    screenBg: "bg-blue-100",
    tag: "bg-blue-50 text-blue-600",
    year: "2026",
    featured: true,
    status: "Completed",
    link: "https://yordsonapartments.com",
    caseStudy: {
      challenge:
        "Yordson Apartments needed a hotel website that could showcase rooms properly and let guests book and pay without back-and-forth over phone or email.",
      solutions: [
        "Built a hotel website with detailed room listings",
        "Added a full booking system with payment integration via Paystack",
        "Automated booking confirmation emails via Resend",
      ],
      gallery: ["/yordsonapartments.png"],
      testimonial: {
        quote:
          "I was referred to you by Mr. Vincent and honestly, you did not disappoint. The logo design was amazing and the website is very responsive. I love the fact that you are very professional and you delivered on time.",
        name: "Yordson Apartments",
        role: "CEO, Yordson Apartments",
      },
    },
  },
  {
    id: 23,
    slug: "ocla-botanicals",
    name: "OCLA Botanicals",
    category: "Web Development",
    type: "web",
    tools: "Next.js · Tailwind · Firebase · Paystack  · Resend",
    desc: "OCLA Botanicals is a bulk botanical supplier for the beauty and wellness industry, offering private label manufacturing, raw oils, butters, and finished haircare products for global brands and wholesalers.",
    image: "/ocla.png",
    screenBg: "bg-blue-100",
    tag: "bg-blue-50 text-blue-600",
    year: "2026",
    featured: true,
    status: "Completed",
    link: "https://oclabotanicals.com",
  },
  {
    id: 24,
    slug: "ocla-equip",
    name: "OCLA Equip",
    category: "Web Development",
    type: "web",
    tools: "Next.js · Tailwind · Firebase · Paystack  · Resend",
    desc: "OCLA Equip supplies industrial equipment — stainless steel mixing tanks, processing systems, filling machinery, and production lines — to manufacturers, factories, and laboratories across Nigeria and Africa.",
    image: "/ocla.png",
    screenBg: "bg-blue-100",
    tag: "bg-blue-50 text-blue-600",
    year: "2026",
    featured: true,
    status: "Completed",
    link: "https://oclaequip.com",
  },
  {
    id: 4,
    slug: "royal-moss-hotel",
    name: "Royal Moss Hotel",
    category: "Web Development",
    type: "web",
    tools: "Next.js · Supabase · Tailwind . Paystack · Resend",
    desc: "An Hotel Management System with booking integration, real-time room availability check, payment integration, authentication and admin management system.",
    image: "/royalmosshotel.png",
    screenBg: "bg-blue-100",
    tag: "bg-blue-50 text-blue-600",
    year: "2026",
    featured: true,
    status: "Completed",
    link: "https://royalmoss.org",
    caseStudy: {
      challenge:
        "Royal Moss Hotel needed a real hotel management system, not just a brochure site — something that could handle live room availability, bookings, and payments end to end.",
      solutions: [
        "Built a full hotel management system with booking integration",
        "Added real-time room availability checking",
        "Integrated Paystack for payment processing",
        "Added authentication and an admin management system for staff",
        "Automated notifications via Resend",
      ],
      gallery: ["/royalmosshotel.png"],
      testimonial: null,
    },
  },
  {
    id: 20,
    slug: "with-love-by-tlg",
    name: "With Love By TLG",
    category: "Web Development",
    type: "web",
    tools: "Next.js · Supabase · Tailwind . PayPal . Resend",
    desc: "A platform that allows Canadians to make donations, purchase event tickets, and participate in fundraising campaigns through a secure and intuitive user experience.",
    image: "/withlove.png",
    screenBg: "bg-blue-100",
    tag: "bg-blue-50 text-blue-600",
    year: "2026",
    featured: true,
    status: "Completed",
    link: "https://withlovebytlg.com",
    caseStudy: {
      challenge:
        "With Love By TLG needed a secure platform for Canadian supporters to donate, buy event tickets, and take part in fundraising campaigns — all in one trustworthy place.",
      solutions: [
        "Built a donations, ticketing, and fundraising campaign platform with event booking and management",
        "Integrated PayPal for secure Canadian payment processing",
        "Added donation management and booking management",
        "Delivered a responsive, sleek design",
        "Added admin management for the platform",
        "Automated confirmation and receipt emails via Resend",
      ],
      gallery: ["/withlove.png"],
      testimonial: null,
    },
  },
  {
    id: 26,
    slug: "ayora-tribe-limited",
    name: "Ayora Tribe Limited",
    category: "Web Development",
    type: "web",
    tools: "Next.js · Tailwind · Firebase · Paystack  · Resend",
    desc: "An E-comerce website for a brand that sells natural, eco-friendly scent experiences and curated gifting for the homes, offices, and corporate spaces.",
    image: "/ayoratribelimited.png",
    screenBg: "bg-blue-100",
    tag: "bg-blue-50 text-blue-600",
    year: "2026",
    featured: true,
    status: "Completed",
    link: "https://ayoratribelimited.com",
    caseStudy: {
      challenge:
        "Ayora Tribe needed an e-commerce site that matched the premium, natural feel of their scent and gifting products — fast, clean, and easy for them to keep updated.",
      solutions: [
        "Built a Next.js e-commerce website for their scent and gifting product line",
        "Integrated Paystack for payments",
        "Automated order emails via Resend",
        "Implemented design changes quickly based on client feedback",
      ],
      gallery: ["/ayoratribelimited.png"],
      testimonial: {
        quote:
          "I love the simplicity of the website design, and how fast you implemented the changes I requested. You also delivered the project on time.",
        name: "Mr Sodiq",
        role: "CEO, Ayora Tribe Limited",
      },
    },
  },
  {
    id: 6,
    slug: "amazon-world",
    name: "Amazon World",
    category: "Web Development",
    type: "web",
    tools: "Next.js · Supabase · Tailwind",
    desc: "An E-commerce website for a clothing brand where users can add to cart, make payment, and admin can list products, and manage products.",
    image: "/amazonworld.png",
    screenBg: "bg-blue-100",
    tag: "bg-blue-50 text-blue-600",
    year: "2026",
    featured: true,
    status: "Completed",
    link: "https://amazonworld.com",
  },
  {
    id: 3,
    slug: "lolaselan",
    name: "LolasElan",
    category: "Web Development",
    type: "web",
    tools: "Next.js · Supabase · Tailwind . Stripe · Carrier · Resend",
    desc: "E-commerce website for cloth listings, cart, Stripe payment integration, Carrier integration, real-time shipping fee calculation, and order tracking, and admin management system.",
    image: "/lolaselan.png",
    screenBg: "bg-blue-100",
    tag: "bg-blue-50 text-blue-600",
    year: "2025",
    featured: true,
    status: "Completed",
    link: "https://shoplolaselan.uk",
  },
  {
    id: 12,
    slug: "haut-logistics",
    name: "Haut Logistics (Web Design)",
    category: "Web Development",
    type: "web",
    tools: "Figma",
    desc: "A Website Redesign of an existing logistics company in Canada.",
    image: "/looksclothing.png",
    screenBg: "bg-amber-100",
    tag: "bg-amber-50 text-amber-700",
    year: "2026",
    featured: true,
    status: "Completed",
    link: "https://hautlogistics.com",
  },
  {
    id: 7,
    slug: "that-local-girl-mobile-app",
    name: "That Local Girl (Mobile App)",
    category: "Mobile App",
    type: "mobile",
    tools: "React Native · Expo · Supabase",
    desc: "E-commerce mobile app with product listings, cart, Paystack checkout, and order tracking.",
    image: "/thatlocalgirlmobileapp.jpg",
    screenBg: "bg-orange-100",
    tag: "bg-orange-50 text-[#FF5C00]",
    year: "2024",
    featured: true,
    status: "Ongoing",
    link: "https://www.figma.com/design/TSZMZQ3E4iBlWYIGFjh9l3/E-Commerce-Shopping-App?t=GCtgR0SKzuiNTdpx-0",
  },
  {
    id: 9,
    slug: "campfleet",
    name: "Campfleet",
    category: "Mobile App",
    type: "mobile",
    tools: "React Native · Node.js · Firebase",
    desc: "An all-in-one campus social network for Nigerian students.",
    image: "/campfleet.png",
    screenBg: "bg-slate-200",
    tag: "bg-slate-100 text-slate-600",
    year: "2026",
    featured: false,
    status: "Ongoing",
    link: null,
  },
  {
    id: 8,
    slug: "mr-vincent-itodo",
    name: "Mr Vincent Itodo",
    category: "Graphic Design",
    type: "design",
    tools: "Figma · Adobe Illustrator",
    desc: "Complete flier design and invitation card design.",
    image: null,
    screenBg: "bg-green-100",
    tag: "bg-green-50 text-green-600",
    year: "2026",
    featured: true,
    status: "Completed",
    link: null,
  },
  {
    id: 13,
    slug: "pockethealth-ng",
    name: "PocketHealth NG",
    category: "Graphic Design",
    type: "design",
    tools: "Figma · Adobe Photoshop",
    desc: "Investor pitch deck design — 24 slides covering product overview, traction, and financials.",
    image: null,
    screenBg: "bg-rose-100",
    tag: "bg-rose-50 text-rose-600",
    year: "2026",
    featured: false,
    status: "Completed",
    link: null,
  },
  {
    id: 14,
    slug: "trenova-logistics-ltd",
    name: "Trenova Logistics Ltd",
    category: "Business Registration",
    type: "registration",
    tools: "CAC · FIRS · SCUML",
    desc: "Full LLC incorporation — CAC registration, TIN, SCUML enrolment, and corporate bank account guidance.",
    image: null,
    screenBg: "bg-teal-100",
    tag: "bg-teal-50 text-teal-600",
    year: "2025",
    featured: false,
    status: "Completed",
    link: null,
  },
  {
    id: 15,
    slug: "obi-catering-co",
    name: "Obi Catering Co.",
    category: "Business Registration",
    type: "registration",
    tools: "CAC · FIRS",
    desc: "Sole proprietorship business name registration with TIN and post-registration compliance checklist.",
    image: null,
    screenBg: "bg-yellow-100",
    tag: "bg-yellow-50 text-yellow-700",
    year: "2025",
    featured: false,
    status: "Completed",
    link: null,
  },
  {
    id: 16,
    slug: "afolabi-chambers",
    name: "Afolabi Chambers",
    category: "Graphic Design",
    type: "design",
    tools: "Adobe Illustrator · Figma",
    desc: "Brand identity refresh — new logo mark, letterhead, business cards, and email signature templates.",
    image: null,
    screenBg: "bg-indigo-100",
    tag: "bg-indigo-50 text-indigo-600",
    year: "2026",
    featured: false,
    status: "Completed",
    link: null,
  },
  {
    id: 17,
    slug: "world-famous-clothing",
    name: "World Famous Clothing",
    category: "Business Registration",
    type: "registration",
    tools: "CAC · Trade Mark",
    desc: "Business name registration with CAC and full trademark filing to protect the brand name and logo.",
    image: null,
    screenBg: "bg-teal-100",
    tag: "bg-teal-50 text-teal-600",
    year: "2025",
    featured: false,
    status: "Completed",
    link: null,
  },
  {
    id: 18,
    slug: "glittering-icon-hub",
    name: "Glittering Icon Hub",
    category: "Business Registration",
    type: "registration",
    tools: "CAC · Trade Mark",
    desc: "Business name registration with CAC and full trademark filing to protect the brand name and logo.",
    image: null,
    screenBg: "bg-teal-100",
    tag: "bg-teal-50 text-teal-600",
    year: "2025",
    featured: false,
    status: "Completed",
    link: null,
  },
  {
    id: 19,
    slug: "laide-luxe-hub",
    name: "Laide Luxe Hub",
    category: "Business Registration",
    type: "registration",
    tools: "CAC · Trade Mark",
    desc: "Business name registration with CAC and full trademark filing to protect the brand name and logo.",
    image: null,
    screenBg: "bg-teal-100",
    tag: "bg-teal-50 text-teal-600",
    year: "2025",
    featured: false,
    status: "Completed",
    link: null,
  },
];
